### ISSUE TITLE
Custom commit message and pull request title won't work

### ISSUE THREAD

**Issue by starikcetin** [saadmk11/github-actions-version-updater#14]
I am using this action as follows:
```yaml
- uses: saadmk11/github-actions-version-updater@v0.5.6
  with:
    commit_message: "chore: update github action versions"
    pull_request_title: "chore: update github action versions"
    token: ${{ secrets.WORKFLOW_SCOPED_ACCESS_TOKEN }}
```

It gives the following warning:
```
Unexpected input(s) 'commit_message', 'pull_request_title', valid inputs are ['entryPoint', 'args', 'committer_username', 'committer_email', 'ignore', 'token']
```
And I get the default pull request title and commit message instead.
