### ISSUE TITLE
0.7.0 fails even if there is no error

### ISSUE THREAD

**Issue by ASarco** [saadmk11/github-actions-version-updater#31]
When running this action, the workflows fails, even if there's no evident error and all the actions are checked:

![image](https://user-images.githubusercontent.com/9863532/197978458-b97b6f15-6707-46d0-8e06-51584ac9cb47.png)

The job is configured like this:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Access token with `workflow` scope is required
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.0
        with:
          # Optional, This will be used to configure git
          # defaults to `github-actions[bot]` if not provided
          #committer_username: 'test'
          #committer_email: 'test@test.com'
          # Optional, allows customizing the commit message and pull request title
          # Both default to 'Update GitHub Action Versions'
          commit_message: 'Github Actions versions have changed'
          pull_request_title: 'Github Actions versions have changed'
          # Access token with `workflow` scope is required
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
          release_types: major
```
