### ISSUE TITLE
"fatal: not in a git directory" after several successful runs

### ISSUE THREAD

**Issue by jmlemetayer** [saadmk11/github-actions-version-updater#49]
The actions were working correctly, and during the last run the error "fatal : not in a git directory" appeared.

The faulty run:
https://github.com/jmlemetayer/project-release/actions/runs/3699984553/jobs/6267948063

The last modification of the workflow was the update of the "actions/checkout" to v3.2.0 (done by the github-actions-version-updater):
https://github.com/jmlemetayer/project-release/commit/a0a4dfdf978d1b67979ca6d8a8df434a303a1c85

**Comment by GopikaV24** [comment]
We are also facing same issue.

**Comment by saadmk11** [comment]
@GopikaV24 Can you please share your workflow file content?

**Comment by GopikaV24** [comment]
Please refer this,
```
name: GitHub Actions Version Updater

# Controls when the action will run.
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.0
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}
          extra_workflow_locations: "./workflows"
```

**Comment by saadmk11** [comment]
Please check if running this command before running GitHub Actions Version Updater works for you

`git config --global --add safe.directory "$GITHUB_WORKSPACE"`

```yaml
- uses: actions/checkout@v3
  with:
    # [Required] Access token with `workflow` scope.
    token: ${{ secrets.WORKFLOW_SECRET }}

- run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

- name: Run GitHub Actions Version Updater
  uses: saadmk11/github-actions-version-updater@v0.7.0
  with:
    # [Required] Access token with `workflow` scope.
    token: ${{ secrets.WORKFLOW_SECRET }}
    extra_workflow_locations: "./workflows"
```

ref: 
- https://github.com/actions/checkout/issues/363
