### ISSUE TITLE
Self hosted :   Error: fatal: not in a git directory

### ISSUE THREAD

**Issue by rahulpatidar0191** [saadmk11/github-actions-version-updater#77]
Similar to https://github.com/saadmk11/github-actions-version-updater/issues/49

It runs fine on the github's runner but seem to fail on the self hosted runner 

We are using `0.7.4` version 

![image](https://github.com/saadmk11/github-actions-version-updater/assets/42219389/86a9a2ae-5c3f-4104-a54f-f176218afb30)

**Comment by saadmk11** [comment]
I have not used self-hosted runners so not sure I can provide much help here. perhaps you can try running 
```yaml
- name: Git Safe Dirrectory
  shell: bash
  run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
```

before the github-actions-version-updater step.
